name: Release monorepo

on:
  workflow_dispatch:
    inputs:
      releaseParams:
        description: 'Pass parameters to lerna publish (ex: major, minor, patch)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'
      - run: git config user.email "-" && git config user.name "🤖 Release Bot"
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - run: pnpm install --frozen-lockfile
      - run: pnpm lerna version --yes --conventional-commits --create-release github ${{ github.event.inputs.releaseParams }}
      - run: pnpm lerna publish from-git --yes
